# Generated by Django 3.2.12 on 2022-04-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
