# Generated by Django 3.2.12 on 2022-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku_nubmer', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('supplier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'ml'), (2, 'g')], default=1)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
