filebeat.inputs:- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log
    
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: afteroutput.elasticsearch:
  hosts: ["http://elasticsearch:9200"]



  # docker restart django_purchasedjango_1 django_storydjango_1 django_messagedjango_1
  # docker restart django_consumer_message_1 django_consumer_purchase_1 django_consumer_story_1