# Generated by Django 3.2.12 on 2022-05-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='quantity',
            new_name='purchase_id',
        ),
    ]
