# Generated by Django 3.2.12 on 2022-04-28 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('status', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Ready'), (4, 'Retrieved'), (5, 'Canceled')], default=1)),
                ('order_number', models.CharField(max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
